[General]
  snippetfile = "/home/yaxin/.config/pet/snippet.toml"
  editor = "/usr/bin/nvim"
  column = 40
  selectcmd = "fzf"
  backend = "gist"
  sortby = ""

[Gist]
  file_name = "pet-snippet.toml"
  access_token = "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"
  gist_id = "0a5da5f0cf3c44547b2513f6f079fc00"
  public = false
  auto_sync = true

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
  skip_ssl = false
