# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin/:/sbin
# set XDG_CONFIG_HOME
if [ -z "${XDG_CONFIG_HOME-}" ]; then
    XDG_CONFIG_HOME="${HOME}/.config"
fi

# Pre zsh config
source $XDG_CONFIG_HOME/zsh/pre-zshrc

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"
if [ -f ~/.zsh_theme ]; then
    ZSH_THEME=$(cat ~/.zsh_theme | head -1)
fi

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# https://stackoverflow.com/questions/25614613/how-to-disable-zsh-substitution-autocomplete-with-url-and-backslashes
DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$XDG_CONFIG_HOME/zsh

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# git clone https://github.com/wting/autojump.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/autojump
# git clone https://github.com/zsh-users/zsh-completions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions
plugins=(
    brew
    sudo history git colored-man-pages tmux
    zsh-autosuggestions
    autojump
    poetry
    iterm2
)
# docker plugin
if which docker &> /dev/null; then
    plugins+=(docker docker-compose)
fi
# kubernetes plugin
if which kubectl &> /dev/null; then
    plugins+=(kubectl)
fi
# archlinux
if grep -i arch /etc/issue &> /dev/null; then
    plugins+=(archlinux)
fi
# fzf, https://github.com/junegunn/fzf
if which fzf &> /dev/null; then
    plugins+=(fzf)
fi
if which pip &> /dev/null; then
    plugins+=(pip)
fi
if which systemctl &> /dev/null; then
    plugins+=(systemd)
fi

source $ZSH/oh-my-zsh.sh

# User configuration
# disable zsh auto correct
unsetopt correct_all
# disable mail check
unset MAILCHECK
# disable history share between sessions
unsetopt share_history
# ignore dump command
setopt HIST_IGNORE_ALL_DUPS
# ignore command start with space
setopt HIST_IGNORE_SPACE
# disable ctrl+d
#set -o ignoreeof

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Plugin setting
[ -d "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions" ] && autoload -U compinit && compinit
[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh && autoload -U compinit && compinit -u

# Reset PATH environment
if [[ "$OSTYPE" = darwin* ]]; then
    PATH=$PATH:/Library/Apple/usr/bin:/Library/Apple/bin
fi

ZSH_CONFIG="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.zsh" || printf %s "${XDG_CONFIG_HOME}/zsh")"
profiles=(
    "$ZSH_CONFIG/zshrc.local" "$ZSH_CONFIG/zshenv" "$ZSH_CONFIG/zsh_func" "$ZSH_CONFIG/zsh_aliases"
    "$ZSH_CONFIG/zshenv.local" "$ZSH_CONFIG/zsh_func.local" "$ZSH_CONFIG/zsh_aliases.local"
)
for profile in $profiles; do
    if [[ -f $profile ]]; then
        source $profile
    fi
done

# Load additional script
if [ -d "$ZSH_CONFIG/zsh.d/" ]; then
    for k in $(ls -1 "$ZSH_CONFIG/zsh.d/"); do
        source "$ZSH_CONFIG/zsh.d/${k}"
    done
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
